local/routes/web.php
<?php

Route::get('seleccionarjornada/{id}', 'EventoAsistenciaController@seleccionjornada');
Route::get('asistencia/{id}', 'EventoAsistenciaController@consultaregistro');
Route::get('asistencia/{id}/{usuario}', 'EventoAsistenciaController@registroasistencia');
Route::resource('eventoasistencia', 'EventoAsistenciaController');

Route::get('/', 'PaginasController@index')->name('casa');

Route::post('enviarmensaje',[
	'uses' =>'PaginasController@enviarmensaje',
	'as'   =>'paginas.enviarmensaje'
]);
Route::post('enviarsolicitud',[
	'uses' =>'PaginasController@enviarsolicitud',
	'as'   =>'paginas.enviarsolicitud'
	]);
Route::post('contratarunachay',[
	'uses' =>'PaginasController@contratarunachay',
	'as'   =>'paginas.contratarunachay'
	]);
Route::post('registrarpersona',[
	'uses' =>'RegistroController@guardar',
	'as'   =>'registrarpersona.guardar'
]);
Route::post('registrarfacturacion',[
	'uses' =>'FacturacionController@store',
	'as'   =>'registrarfacturacion.store'
]);
Route::get('administracion', 'BackendController@index');
Route::get('/login', 'HomeController@index');
Auth::routes();
Route::get('/logout', 'Auth\LoginController@logout')->name('logout' );
Route::get('/home', 'HomeController@index')->name('home');
// Route::get('logout', 'LogController@logout');
Route::get('administracion', 'BackendController@index');
Route::resource('categorias','CategoriasController');
Route::get('categorias/{id}/destroy',[
	'uses' =>'CategoriasController@destroy',
	'as'   =>'categorias.destroy'
	]);
Route::resource('articulos', 'ArticulosController');
Route::get('articulos/{id}/destroy',[
			'uses' => 'ArticulosController@destroy',
			'as'   => 'articulos.destroy'
		]);
Route::resource('animacion', 'SliderController');
Route::get('animacion/{id}/destroy',[
			'uses' => 'SliderController@destroy',
			'as'   => 'animacion.destroy'
		]);
Route::resource('informacion', 'InformacionController');
Route::get('informacion/{id}/destroy',[
			'uses' => 'InformacionController@destroy',
			'as'   => 'informacion.destroy'
		]);
Route::get('imagen/{id}/destroy',[
			'uses' => 'ImagenesController@destroy',
			'as'   => 'imagen.destroy'
		]);
Route::resource('video', 'VideoController');
Route::get('video/{id}/destroy',[
			'uses' => 'VideoController@destroy',
			'as'   => 'video.destroy'
		]);
// Route::resource('galeria', 'FotosController');
// Route::get('galeria/{id}/destroy',[
			// 			'uses' => 'FotosController@destroy',
			// 			'as'   => 'galeria.destroy'
		// 		]);
Route::resource('tags', 'TagsController');
Route::get('tags/{id}/destroy',[
			'uses' => 'TagsController@destroy',
			'as'   => 'tags.destroy'
		]);
Route::resource('tipos-usuarios','TiposController');
Route::resource('usuarios','UsuariosController');
Route::resource('camposextrasgrupos','CamposExtrasGruposController');
Route::get('camposextrasgrupos/{id}/destroy',[
			'uses' => 'CamposExtrasGruposController@destroy',
			'as'   => 'camposextrasgrupos.destroy'
		]);
Route::resource('camposextras','CamposExtrasController');
Route::resource('obtener','AjaxController');
Route::get('camposextras/{id}/destroy',[
			'uses' => 'CamposExtrasController@destroy',
			'as'   => 'camposextras.destroy'
		]);
Route::resource('registro','RegistrosController');
Route::get('autorizado','RegistrosController@autorizado');
Route::get('confirmacion/{codigo}', 'RegistrosController@confirmar');
Route::get('contrasena','RegistrosController@contrasena');
Route::post('recuperacion', ['as' => 'GuardarRecuperacion', 'uses' => 'RegistrosController@guardarrecuperacion']);
Route::post('restablecer', ['as' => 'GuardarRestablecer', 'uses' => 'RegistrosController@guardarrestablecer']);
Route::get('env/{id}','RegistrosController@envio');
Route::get('reestablecer/{codigo}','RegistrosController@busqueda');
Route::resource('solicitudes','RegistrosController@solicitudes');
Route::get('habilitarusuario/{id}', ['as' => 'hab_user', 'uses' => 'RegistrosController@habilitar_usuario']);
Route::resource('activaciones','ArticulosController@activaciones');
Route::get('activararticulo/{id}', ['as' => 'hab_articulo', 'uses' => 'RegistrosController@habilitararticulo']);
//Route::post('registro','UsuariosController@registro');
//Route::get('registro', ['as' => 'registro', 'uses' => 'UsuariosController@registro']);
//////////////////
Route::resource('categoriainterna','CategoriaInternaController');
Route::get('categoriainterna/{id}/destroy',[
	'uses' =>'CategoriaInternaController@destroy',
	'as'   =>'categoriainterna.destroy'
	]);
//Route::get('/publica', 'LogController@publicar');
//Route::get('/goo', 'LogController@iniciagoogle');
Route::post('/upload', 'ArticulosController@subirfotogaleria');
Route::post('/uploaddoc', 'ArticulosController@subirdoc');
Route::get('/infoevento', 'PaginasController@infoeventos');
Route::get('/pruebaa', 'ArticulosController@pruebaa');
//Route::get('/contratarunachay', function(){return view('paginas/contratarrunachay'); });
//Route::get('/formulario', function(){return view('paginas/formulario'); });
Route::get('formfacturacion/{id}','FacturacionController@ue');
Route::resource('formregistro','RegistroController');
Route::resource('formfacturacion','FacturacionController');
//Route::get('/formulario-facturacion', function(){return view('paginas/facturacion'); });
// Route::get('/confirmacion', function(){
	// 	return view('paginas/confirmacion');
// });
//Route::get('/formulario-facturacion-mercedarias', function(){return view('paginas/facturacion/mercedarias'); });
// Route::get('/jornada-docentes', function(){
	// 	return view('paginas/conferencia.index');
// });
// Route::get('/confirmaregistro', 'WebinarRegistroController@confirmaregistro');
Route::get('/confirmaregistro/{id}',[
	'uses' => 'WebinarRegistroController@confirmaregistro',
	'as'   => 'webinar.confirmaregistro'
]);
//
Route::resource('WebinarRegistro','WebinarRegistroController');
// Route::get('/confirmacion/', 'WebinarRegistroController@store');
Route::get('lista-asistentes-excel','WebinarController@exportExcel')->name('asistentes.excel');
Route::resource('imagen', 'ImagenesController');
Route::resource('webinar', 'WebinarController');
Route::resource('ponentes', 'PonentesController');
Route::resource('asignarponentes', 'AsignarPonentesController');
Route::resource('asignardias', 'AsignarDiaController');
Route::resource('calificacionponente', 'CalificacionPonenteController');
Route::get('calificaciones-ponente/{id_dia_ponente}/{id_ponente}/',[
			'uses' => 'AsignarPonentesController@mostrar_calificaciones',
			'as'   => 'asignarponentes.mostrar'
		]);
Route::get('ponentes_dia/{id}/',[
			'uses' => 'WebinarController@add',
			'as'   => 'webinar.add'
		]);
Route::get('asistencias/{id}/',[
			'uses' => 'WebinarController@show_asistencia',
			'as'   => 'webinar.asis'
		]);

Route::get('imprimirqr/{id}/',[
			'uses' => 'WebinarRegistroController@descargarqr',
			'as'   => 'WebinarRegistro.qr'
		]);

Route::get('asistentes_cumplidos/{id}/',[
			'uses' => 'WebinarController@show_aprobados',
			'as'   => 'webinar.aprob'
		]);

Route::put('cambiarestado/{id}/',[
			'uses' => 'AsignarDiaController@cambiarestado',
			'as'   => 'asignardias.cambiarestado'
		]);
Route::get('dias_evento/{id}/',[
			'uses' => 'WebinarController@dates',
			'as'   => 'webinar.dates'
		]);
Route::get('asistencia_evento/{id}/',[
			'uses' => 'AsignarDiaController@asis',
			'as'   => 'asignardias.asis'
		]);
Route::get('destroyponente/{id}/',[
			'uses' => 'WebinarController@destroyponente',
			'as'   => 'webinar.destroyponente'
		]);
//Route::get('/transmision', function(){return view("paginas.transmision");});
// Route::get('/enviarasistencia', function(){return view("admin.webinar.enviarasistencia");});
Route::get('enviarasistencia/{id}/{salto}/',[
			'uses' => 'WebinarController@envasistencia',
			'as'   => 'webinar.envasist'
		]);
Route::get('enviarasistenciaunico/{id}/{id_reg}/',[
			'uses' => 'WebinarController@enviarAsistenciaUnico',
			'as'   => 'webinar.envasist1'
		]);

Route::get('enviarcertificado/{id}/{salto}/',[
			'uses' => 'WebinarController@envcertificado',
			'as'   => 'webinar.envcert'
		]);
Route::get('enviarcertificadounico/{id}/{id_reg}/',[
			'uses' => 'WebinarController@envcertificadounico',
			'as'   => 'webinar.envcertunico'
		]);


Route::get('{id}', 'WebinarRegistroController@registrowebinar');

Route::get('reserva/{id}', 'WebinarRegistroController@reserva');

Route::get('{id}/buscar_certificado', 'WebinarRegistroController@generar_certificado');

Route::get('buscarcertificado/{id_evento}/{id_asistente}', 'WebinarRegistroController@pagina_compartir');

Route::post('certificado/',[
			'uses' => 'WebinarRegistroController@certificado',
			'as'   => 'WebinarRegistro.certificado'
		]);

Route::post('descargar/',[
			'uses' => 'WebinarRegistroController@descargar',
			'as'   => 'WebinarRegistro.descargar'
		]);

local/app/Articulo.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
// use Cviebrock\EloquentSluggable\SluggableInterface;
// use Cviebrock\EloquentSluggable\SluggableTrait;

// class Articulo extends Model implements SluggableInterface
class Articulo extends Model
{

    // use SluggableTrait;

    // protected $sluggable = [
    //     'build_from' => 'titulo',
    //     'save_to'    => 'slug',
    // ];


    //
  protected $table = 'articulos';

  protected $fillable = ['longitud','latitud','titulo', 'slug', 'texto','id_categoria', 'activo', 'destacado',  'path',  'rutadoc','id_usuario', 'seo_keyword', 'seo_descripcion','fechainicio','fechafin','lugar','id_prioridad','descripcionredes'];

  protected $hidden = [];



     public function categoria()
    {
        return $this->belongsTo('App\Categoria');
    }
    public function usuario()
    {
        return $this->belongsTo('App\User');
    }

     public function tags()
    {
        return $this->belongsToMany('App\Tag');
    }

     public function fotos()
    {
        return $this->belongsToMany('App\Foto');
    }



}

local/app/Http/Controllers/activacion.blade.php
<div style="font-family:'Droid Sans',Arial,Verdana;color:#393a3f;font-size:13px;line-height:20px"><div class="adM">
</div><div style="border:5px #eeeeee solid;margin:5px;border-radius:10px;background:#fff;width:615px"><div class="adM">
    </div><div style="background:#eeeeee;padding:10px;width:595px"><div class="adM">
        </div><img src="http://casasvacacionales.com.ec/assets/img/logo-color-big.png" class="CToWUd">
    </div>
    <div style="padding:10px">
        Usuario/a {{$nombres}} {{$apellidos}},<br>
<br>
¡Gracias por unirte a Casas Vacacionales!<br>
<br>
Informamos que su cuenta ha sido activada por el administrador del sitio.<br>
 <br>
        <br>
        Saludos cordiales,<br>
        <br>
        El equipo Casas de vacaciones<br>
        <a href="http://www.casasdevacaciones.com.ec">http://www.casasdevacaciones.<wbr>com.ec</a><br>
        Correo electrónico: <a href="mailto:soporte@casasdevacaciones.com.mx" target="_blank">info@casasdevacaciones.com.<wbr>ec</a><br>
        Teléfono: 593

        
    </div>
    <div style="color:#929292;font-size:11px;padding:10px 30px;text-align:center">
        <p style="margin:0"></p>
    </div>
</div>
<img src="" style="width:1px;height:1px" alt="" class="CToWUd"></div>

local/resources/views/admin/articulos/activacion.blade.php
@extends('layouts.backend')



@section('titulo')
SOLICITUDES DE INGRESO AL SISTEMA
@stop

@section('contenido')

@if(Session::has('message'))
<div class="alert alert-warning alert-dismissible" role="alert">
  <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
  {{Session::get('message')}}
</div>


@endif


<br>
 
<a class="btn btn-primary" href="{{ URL::route('articulos.create') }}">Nuevo</a>
<br>
@if (count($articulos))

<br>
    <div class="row">
      <div class="col-md-12">     


        <div class="box">
           
            <!-- /.box-header -->
            <div class="box-body">   

          <table  id="tbbuzon" class="table table-striped table-bordered table-hover display" >
            <thead>
              <th>#</th>
              <th>ID</th>
              <th>Título</th>
              <th style="width:30%;">Contenido</th>
              <th>Autor</th>
              <th>Categoria</th>
              <th>Imagen</th>
              <th>Acciones</th>
            </thead>

            <tbody>
              <tr>
                <?php $s = 0 ; ?>
                @foreach ($articulos as $articulo)
                <td>{{$articulo->id}}</td>
                <td> <?php $s = $s + 1; echo $s; ?></td>
                <td>{{$articulo->titulo}}</td>
                <td><?php $ser1 = substr($articulo->texto,0,200); echo strip_tags($ser1); ?></td>
                <td>{{$articulo->nombres}}</td>
                <td>{{$articulo->categoria}}</td>
                @if(empty($articulo->path))
                  <td><img src="{{asset('assets/images')}}/no-imagen.jpg"  style ="width: 50px; height: 50px!important;object-fit: cover!important;"></td>
                @else
                  <td>

                     <div class="lightBoxGallery">
                            <a href="{{asset('local/public/images')}}/{{$articulo->path}}" title="Image from Unsplash" data-gallery="">
                              <img  style="width: 50px;height: 50px!important;"  src="{{asset('local/public/images')}}/{{$articulo->path}}">
                            </a>
                           
                 

                            <!-- The Gallery as lightbox dialog, should be a child element of the document body -->
                            <div id="blueimp-gallery" class="blueimp-gallery">
                                <div class="slides"></div>
                                <h3 class="title"></h3>
                                <a class="prev">‹</a>
                                <a class="next">›</a>
                                <a class="close">×</a>
                                <a class="play-pause"></a>
                                <ol class="indicator"></ol>
                            </div>

                        </div>
                  
                  </td>
                @endif
                <td>

                {!! Form::open(array('method' => 'GET', 'route' => array('hab_articulo', $articulo->id))) !!}                       
                         {!! Form::submit('Activar', array('class' => 'btn btn-primary')) !!}
                       {!! Form::close() !!}
                <a class="btn btn-success" href="{{route('articulos.edit', $articulo->id)}}" role="button"><i class="fa fa-pencil-square-o"></i></a>
                    <a class="btn btn-danger" href="{{route('articulos.destroy', $articulo->id)}}" onclick="return confirm('Quiere borrar el registro?')" role="button"><i class="fa fa-trash-o"></i></a>
                
                </td>

              </tr>
              @endforeach
            </tbody>
          </table>

         

      </div>
   
    </div>
      </div>
   
    </div>

@else
    No hay Artículos
@endif





@endsection

local/resources/views/admin/articulos/index.blade.php
@extends('layouts.backend')

@section('titulo')
  Artículos
@stop

@section('contenido')

@if(Session::has('message'))
<div class="alert alert-warning alert-dismissible" role="alert">
  <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
  {{Session::get('message')}}
</div>


@endif


<br>

<a class="btn btn-primary" href="{{ URL::route('articulos.create') }}">Nuevo</a>
<br>
@if (count($articulos))

<br>
    <div class="row">
      <div class="col-md-12">


        <div class="box">

            <!-- /.box-header -->
            <div class="box-body">

          <table  id="tbbuzon" class="table table-striped table-bordered table-hover display" >
            <thead>
              <th>#</th>
              <th>ID</th>
              <th>Título</th>
              <th style="width:30%;">Contenido</th>
              <th>Autor</th>
              <th>Activado</th>
              <th>Categoria</th>
              <th>Imagen</th>
              <th>Acciones</th>
            </thead>

            <tbody>
              <tr>
                <?php $s = 0 ; ?>
                @foreach ($articulos as $articulo)
                <td>{{$articulo->id}}</td>
                <td> <?php $s = $s + 1; echo $s; ?></td>
                <td>{{$articulo->titulo}}</td>
                <td><?php $ser1 = substr($articulo->texto,0,200); echo strip_tags($ser1); ?></td>
                <td>{{$articulo->nombres}}</td>
                <td>
                <?php if ($articulo->activado == true) {
                  echo "SI";
                }else{
                  echo "NO";
                }
                 ?>

                </td>
                <td>{{$articulo->categoria}}</td>
                @if(empty($articulo->path))
                  <td><img src="{{asset('assets/images')}}/no-imagen.jpg" onerror=" this.src = 'local/public/images/articulo.png';" style ="width: 50px; height: 50px!important;object-fit: cover!important;"></td>
                @else
                  <td>

                     <div class="lightBoxGallery">
                            <a href="{{asset('local/public/images')}}/{{$articulo->path}}" title="Image from Unsplash" data-gallery="">
                              <img  style="width: 50px;height: 50px!important;"  src="{{asset('local/public/images')}}/{{$articulo->path}}" onerror="this.src = 'local/public/images/articulo.png';" >
                            </a>

                            <!-- The Gallery as lightbox dialog, should be a child element of the document body -->
                            <div id="blueimp-gallery" class="blueimp-gallery">
                                <div class="slides"></div>
                                <h3 class="title"></h3>
                                <a class="prev">‹</a>
                                <a class="next">›</a>
                                <a class="close">×</a>
                                <a class="play-pause"></a>
                                <ol class="indicator"></ol>
                            </div>

                        </div>

                  </td>
                @endif
                <td><a class="btn btn-success" href="{{route('articulos.edit', $articulo->id)}}" role="button"><i class="fa fa-pencil-square-o"></i></a>
                    <a class="btn btn-danger" href="{{route('articulos.destroy', $articulo->id)}}" onclick="return confirm('Quiere borrar el registro?')" role="button"><i class="fa fa-trash-o"></i></a>
                </td>

              </tr>
              @endforeach
            </tbody>
          </table>



      </div>

    </div>
      </div>

    </div>
    <script>
      function accents_supr(data){
        return ! data ?
        '' :
        typeof data === 'string' ?
        data
        .replace( /\n/g, ' ' )
        .replace( /[áàäâ]/g, 'a' )
        .replace( /[éèëê]/g, 'e' )
        .replace( /[íìïî]/g, 'i' )
        .replace( /[óòöô]/g, 'o' )
        .replace( /[úùüû]/g, 'u' ):
        data;

        jQuery.extend( jQuery.fn.dataTableExt.oSort,
        {
          "spanish-string-asc"  : function (s1, s2) { return s1.localeCompare(s2); },
          "spanish-string-desc" : function (s1, s2) { return s2.localeCompare(s1); }
        });

        jQuery.fn.DataTable.ext.type.search['spanish-string'] = function ( data ) {
          return accents_supr(data);
        }
      }


      jQuery.fn.DataTable.ext.type.search.string = function ( data ) {
        return ! data ?
        '' :
        typeof data === 'string' ?
        data
        .replace( /έ/g, 'ε' )
        .replace( /[ύϋΰ]/g, 'υ' )
        .replace( /ό/g, 'ο' )
        .replace( /ώ/g, 'ω' )
        .replace( /ά/g, 'α' )
        .replace( /[ίϊΐ]/g, 'ι' )
        .replace( /ή/g, 'η' )
        .replace( /\n/g, ' ' )
        .replace( /á/g, 'a' )
        .replace( /é/g, 'e' )
        .replace( /í/g, 'i' )
        .replace( /ó/g, 'o' )
        .replace( /ú/g, 'u' )
        .replace( /ê/g, 'e' )
        .replace( /î/g, 'i' )
        .replace( /ô/g, 'o' )
        .replace( /è/g, 'e' )
        .replace( /ï/g, 'i' )
        .replace( /ü/g, 'u' )
        .replace( /ã/g, 'a' )
        .replace( /õ/g, 'o' )
        .replace( /ç/g, 'c' )
        .replace( /ì/g, 'i' ) :
        data;
      };
    </script>

    @else
    No hay Artículos
@endif





@endsection