local/routes/web.php
<?php

Route::get('seleccionarjornada/{id}', 'EventoAsistenciaController@seleccionjornada');
Route::get('asistencia/{id}', 'EventoAsistenciaController@consultaregistro');
Route::get('asistencia/{id}/{usuario}', 'EventoAsistenciaController@registroasistencia');
Route::resource('eventoasistencia', 'EventoAsistenciaController');

Route::get('/', 'PaginasController@index')->name('casa');

Route::post('enviarmensaje',[
	'uses' =>'PaginasController@enviarmensaje',
	'as'   =>'paginas.enviarmensaje'
]);
Route::post('enviarsolicitud',[
	'uses' =>'PaginasController@enviarsolicitud',
	'as'   =>'paginas.enviarsolicitud'
	]);
Route::post('contratarunachay',[
	'uses' =>'PaginasController@contratarunachay',
	'as'   =>'paginas.contratarunachay'
	]);
Route::post('registrarpersona',[
	'uses' =>'RegistroController@guardar',
	'as'   =>'registrarpersona.guardar'
]);
Route::post('registrarfacturacion',[
	'uses' =>'FacturacionController@store',
	'as'   =>'registrarfacturacion.store'
]);
Route::get('administracion', 'BackendController@index');
Route::get('/login', 'HomeController@index');
Auth::routes();
Route::get('/logout', 'Auth\LoginController@logout')->name('logout' );
Route::get('/home', 'HomeController@index')->name('home');
// Route::get('logout', 'LogController@logout');
Route::get('administracion', 'BackendController@index');
Route::resource('categorias','CategoriasController');
Route::get('categorias/{id}/destroy',[
	'uses' =>'CategoriasController@destroy',
	'as'   =>'categorias.destroy'
	]);
Route::resource('articulos', 'ArticulosController');
Route::get('articulos/{id}/destroy',[
			'uses' => 'ArticulosController@destroy',
			'as'   => 'articulos.destroy'
		]);
Route::resource('animacion', 'SliderController');
Route::get('animacion/{id}/destroy',[
			'uses' => 'SliderController@destroy',
			'as'   => 'animacion.destroy'
		]);
Route::resource('informacion', 'InformacionController');
Route::get('informacion/{id}/destroy',[
			'uses' => 'InformacionController@destroy',
			'as'   => 'informacion.destroy'
		]);
Route::get('imagen/{id}/destroy',[
			'uses' => 'ImagenesController@destroy',
			'as'   => 'imagen.destroy'
		]);
Route::resource('video', 'VideoController');
Route::get('video/{id}/destroy',[
			'uses' => 'VideoController@destroy',
			'as'   => 'video.destroy'
		]);
// Route::resource('galeria', 'FotosController');
// Route::get('galeria/{id}/destroy',[
			// 			'uses' => 'FotosController@destroy',
			// 			'as'   => 'galeria.destroy'
		// 		]);
Route::resource('tags', 'TagsController');
Route::get('tags/{id}/destroy',[
			'uses' => 'TagsController@destroy',
			'as'   => 'tags.destroy'
		]);
Route::resource('tipos-usuarios','TiposController');
Route::resource('usuarios','UsuariosController');
Route::resource('camposextrasgrupos','CamposExtrasGruposController');
Route::get('camposextrasgrupos/{id}/destroy',[
			'uses' => 'CamposExtrasGruposController@destroy',
			'as'   => 'camposextrasgrupos.destroy'
		]);
Route::resource('camposextras','CamposExtrasController');
Route::resource('obtener','AjaxController');
Route::get('camposextras/{id}/destroy',[
			'uses' => 'CamposExtrasController@destroy',
			'as'   => 'camposextras.destroy'
		]);
Route::resource('registro','RegistrosController');
Route::get('autorizado','RegistrosController@autorizado');
Route::get('confirmacion/{codigo}', 'RegistrosController@confirmar');
Route::get('contrasena','RegistrosController@contrasena');
Route::post('recuperacion', ['as' => 'GuardarRecuperacion', 'uses' => 'RegistrosController@guardarrecuperacion']);
Route::post('restablecer', ['as' => 'GuardarRestablecer', 'uses' => 'RegistrosController@guardarrestablecer']);
Route::get('env/{id}','RegistrosController@envio');
Route::get('reestablecer/{codigo}','RegistrosController@busqueda');
Route::resource('solicitudes','RegistrosController@solicitudes');
Route::get('habilitarusuario/{id}', ['as' => 'hab_user', 'uses' => 'RegistrosController@habilitar_usuario']);
Route::resource('activaciones','ArticulosController@activaciones');
Route::get('activararticulo/{id}', ['as' => 'hab_articulo', 'uses' => 'RegistrosController@habilitararticulo']);
//Route::post('registro','UsuariosController@registro');
//Route::get('registro', ['as' => 'registro', 'uses' => 'UsuariosController@registro']);
//////////////////
Route::resource('categoriainterna','CategoriaInternaController');
Route::get('categoriainterna/{id}/destroy',[
	'uses' =>'CategoriaInternaController@destroy',
	'as'   =>'categoriainterna.destroy'
	]);
//Route::get('/publica', 'LogController@publicar');
//Route::get('/goo', 'LogController@iniciagoogle');
Route::post('/upload', 'ArticulosController@subirfotogaleria');
Route::post('/uploaddoc', 'ArticulosController@subirdoc');
Route::get('/infoevento', 'PaginasController@infoeventos');
Route::get('/pruebaa', 'ArticulosController@pruebaa');
//Route::get('/contratarunachay', function(){return view('paginas/contratarrunachay'); });
//Route::get('/formulario', function(){return view('paginas/formulario'); });
Route::get('formfacturacion/{id}','FacturacionController@ue');
Route::resource('formregistro','RegistroController');
Route::resource('formfacturacion','FacturacionController');
//Route::get('/formulario-facturacion', function(){return view('paginas/facturacion'); });
// Route::get('/confirmacion', function(){
	// 	return view('paginas/confirmacion');
// });
//Route::get('/formulario-facturacion-mercedarias', function(){return view('paginas/facturacion/mercedarias'); });
// Route::get('/jornada-docentes', function(){
	// 	return view('paginas/conferencia.index');
// });
// Route::get('/confirmaregistro', 'WebinarRegistroController@confirmaregistro');
Route::get('/confirmaregistro/{id}',[
	'uses' => 'WebinarRegistroController@confirmaregistro',
	'as'   => 'webinar.confirmaregistro'
]);
//
Route::resource('WebinarRegistro','WebinarRegistroController');
// Route::get('/confirmacion/', 'WebinarRegistroController@store');
Route::get('lista-asistentes-excel','WebinarController@exportExcel')->name('asistentes.excel');
Route::resource('imagen', 'ImagenesController');
Route::resource('webinar', 'WebinarController');
Route::resource('ponentes', 'PonentesController');
Route::resource('asignarponentes', 'AsignarPonentesController');
Route::resource('asignardias', 'AsignarDiaController');
Route::resource('calificacionponente', 'CalificacionPonenteController');
Route::get('calificaciones-ponente/{id_dia_ponente}/{id_ponente}/',[
			'uses' => 'AsignarPonentesController@mostrar_calificaciones',
			'as'   => 'asignarponentes.mostrar'
		]);
Route::get('ponentes_dia/{id}/',[
			'uses' => 'WebinarController@add',
			'as'   => 'webinar.add'
		]);
Route::get('asistencias/{id}/',[
			'uses' => 'WebinarController@show_asistencia',
			'as'   => 'webinar.asis'
		]);

Route::get('imprimirqr/{id}/',[
			'uses' => 'WebinarRegistroController@descargarqr',
			'as'   => 'WebinarRegistro.qr'
		]);

Route::get('asistentes_cumplidos/{id}/',[
			'uses' => 'WebinarController@show_aprobados',
			'as'   => 'webinar.aprob'
		]);

Route::put('cambiarestado/{id}/',[
			'uses' => 'AsignarDiaController@cambiarestado',
			'as'   => 'asignardias.cambiarestado'
		]);
Route::get('dias_evento/{id}/',[
			'uses' => 'WebinarController@dates',
			'as'   => 'webinar.dates'
		]);
Route::get('asistencia_evento/{id}/',[
			'uses' => 'AsignarDiaController@asis',
			'as'   => 'asignardias.asis'
		]);
Route::get('destroyponente/{id}/',[
			'uses' => 'WebinarController@destroyponente',
			'as'   => 'webinar.destroyponente'
		]);
//Route::get('/transmision', function(){return view("paginas.transmision");});
// Route::get('/enviarasistencia', function(){return view("admin.webinar.enviarasistencia");});
Route::get('enviarasistencia/{id}/{salto}/',[
			'uses' => 'WebinarController@envasistencia',
			'as'   => 'webinar.envasist'
		]);
Route::get('enviarasistenciaunico/{id}/{id_reg}/',[
			'uses' => 'WebinarController@enviarAsistenciaUnico',
			'as'   => 'webinar.envasist1'
		]);

Route::get('enviarcertificado/{id}/{salto}/',[
			'uses' => 'WebinarController@envcertificado',
			'as'   => 'webinar.envcert'
		]);
Route::get('enviarcertificadounico/{id}/{id_reg}/',[
			'uses' => 'WebinarController@envcertificadounico',
			'as'   => 'webinar.envcertunico'
		]);


Route::get('{id}', 'WebinarRegistroController@registrowebinar');

Route::get('reserva/{id}', 'WebinarRegistroController@reserva');

Route::get('{id}/buscar_certificado', 'WebinarRegistroController@generar_certificado');

Route::get('buscarcertificado/{id_evento}/{id_asistente}', 'WebinarRegistroController@pagina_compartir');

Route::post('certificado/',[
			'uses' => 'WebinarRegistroController@certificado',
			'as'   => 'WebinarRegistro.certificado'
		]);

Route::post('descargar/',[
			'uses' => 'WebinarRegistroController@descargar',
			'as'   => 'WebinarRegistro.descargar'
		]);

local/app/Ponente.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Ponente extends Model
{


	public function getNombreAndApellidoAttribute()
	{
	    return $this->nombres . ' ' . $this->apellidos;
	}
    //
    protected $table = 'ponentes';

    protected $fillable = ['id', 'apellidos','nombres','foto', 'profesion', 'link_fb', 'link_tw', 'link_inst', 'link_linke', 'estado'];

 	protected $hidden = [];

 	// public function setPathAttribute($path){

  //       if(!empty($path)){
  //         $nombre = $path->getClientOriginalName();
  //         $this->attributes['path'] = $nombre;
  //         \Storage::disk('local')->put($nombre, \File::get($path));
  //       }

  //    }
}

local/app/Http/Controllers/PonentesController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;
use App\Ponente;
use View;
use Session;
use Redirect;
use File;
use Illuminate\Support\Facades\DB;
use App\Http\Requests\ImagenesActualizarRequest;
use App\Http\Requests\PonentesActualizarRequest;
use App\Http\Requests\PonentesCrearRequest;
use Maatwebsite\Excel\Facades\Excel;
use App\Exports\AsistentesExport;




use Illuminate\Support\Facades\Input;


class PonentesController extends Controller
{
     public function __construct()
    {
        $this->middleware('auth');
    }


 public function limpiar_caracteres_especiales($s) {
      $s = str_replace("á","a",$s);
      $s = str_replace("Á","A",$s);
      $s = str_replace("é","e",$s);
      $s = str_replace("É","E",$s);
      $s = str_replace("í","i",$s);
      $s = str_replace("Í","I",$s);
      $s = str_replace("ó","o",$s);
      $s = str_replace("Ó","O",$s);
      $s = str_replace("ú","u",$s);
      $s = str_replace("Ú","U",$s);
      $s = str_replace(" ","-",$s);
      $s = str_replace("´","-",$s);
      $s = str_replace("ñ","n",$s);
      $s = str_replace("Ñ","N",$s);
      //para ampliar los caracteres a reemplazar agregar lineas de este tipo:
      //$s = str_replace("caracter-que-queremos-cambiar","caracter-por-el-cual-lo-vamos-a-cambiar",$s);
      return $s;
    }

    public function index()
    {
        //
        
         $ponentes = Ponente::all();
 
        return View::make('admin.ponentes.index', compact('ponentes'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        // 
        //return view('admin.imagen.crear');
         return View::make('admin.ponentes.crear');
    }

    

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(PonentesCrearRequest $request)
    {
        //
        $ponentes = new Ponente($request->all());
        ////////////////////////////////// imagenprincipal
        $foto = $ponentes->foto;
       
        $dir = public_path().'/images/';
        $docs = $request->file('foto');
        //dd($docs);
        if (Input::hasFile('foto')){

            $foto = $docs->getClientOriginalName();
            $foto = $this->limpiar_caracteres_especiales($foto);
            //dd($imagenprincipal);
            $docs->move($dir, $foto);
        }
        
        ///////////////////////////////////
        $ponentes->foto = $foto;

        
         /////////////////////////////////////////// anuncio
        
        $ponentes->save();
        Session::flash('message','Ponente guardado correctamente');
        return redirect::to('ponentes');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */


    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
         $ponentes= Ponente::find($id);
       return view('admin.ponentes.editar',compact('ponentes'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(PonentesActualizarRequest $request, $id)
    {
        //
         $ponentes= Ponente::find($id);
         $ponentes->fill($request->all());

        ////////////////////////////////// imagenprincipal
        $foto = $ponentes->foto;
       
        $dir = public_path().'/images/';
        $docs = $request->file('foto');
        //dd($docs);
        if (Input::hasFile('foto')){

            $foto = $docs->getClientOriginalName();
            $foto = $this->limpiar_caracteres_especiales($foto);
            //dd($imagenprincipal);
            $docs->move($dir, $foto);
        }
        
        ///////////////////////////////////
        $ponentes->foto = $foto;

        $ponentes->save();
         Session::flash('message','Registro actualizado correctamente');
        return redirect::to('ponentes');

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
        $ponentes = Ponente::find($id);

        $dir = public_path().'/images/';
            File::delete($dir.$ponentes->foto);
        

    
        Ponente::destroy($id);

        Session::flash('message','Ponente eliminado Correctamente');
        return redirect::to('ponentes') ;
    }
}

local/resources/views/admin/ponentes/consult.blade.php
@extends('layouts.backend')

 

@section('titulo')
Imágenes
@stop

@section('contenido')

@include('alerts.success')

 


@if (count($asistentes))

<!--<button id="botonExcel">EXPORTAR</button>-->
<button id="botonExce" onclick="exportTableToExcel('tablaexportar')">EXPORTAR</button>

<div id="impresionExcelDiv" name="impresionExcelDiv" style="display: none;">
    <table  id="tablaexportar" class="table" >
        <thead>
            <tr>
                
                <th>Nombres</th>
                <th>Apellidos</th>
                <th>EMAIL</th>
                <th>Ciudad</th>
                <th>Telefono</th>
                <th>Institucion</th>
                <th>Cargo</th>
            </tr>
        </thead>

        <tbody>
            @foreach ($asistentesex as $asistentesex)
                <tr>
                <td>{{ $asistentesex->nombres }}</td>
                <td>{{ $asistentesex->apellidos }}</td>
                <td>{{ $asistentesex->email }}</td>
                <td>{{ $asistentesex->ciudad }}</td>
                <td>{{ $asistentesex->telefono }}</td>
                <td>{{ $asistentesex->institucion }}</td>
                <td>{{ $asistentesex->cargo }}</td>
                </tr>
            @endforeach
        </tbody>
    </table>
 </div>

    <table  id="tbbuzon" class="table table-striped table-bordered table-hover display" >
        <thead>
            <tr>
                
                <th>Nombres</th>
                <th>Apellidos</th>
                <th>EMAIL</th>
                <th>Ciudad</th>
                <th>Telefono</th>
                <th>Institucion</th>
                <th>Cargo</th>
                <!--<th>ACCIONES</th>-->
            </tr>
        </thead>

        <tbody>
            @foreach ($asistentes as $asistentes)
                <tr>
                <td>{{ $asistentes->nombres }}</td>
                <td>{{ $asistentes->apellidos }}</td>
                <td>{{ $asistentes->email }}</td>
                <td>{{ $asistentes->ciudad }}</td>
                <td>{{ $asistentes->telefono }}</td>
                <td>{{ $asistentes->institucion }}</td>
                <td>{{ $asistentes->cargo }}</td>
                <!--<td>
                    <a class="btn btn-success" href="{{route('WebinarRegistro.edit', $asistentes->id)}}" role="button">
                        <i class="fa fa-pencil-square-o"></i>
                    </a>
                    {!! Form::open(array('method' => 'DELETE', 'route' => array('WebinarRegistro.destroy', $webi->id))) !!}
                        <button type="submit" onclick="return confirm('Quiere borrar el registro?')" class="btn btn-danger"><span class="fa fa-trash-o"></span></button>
                    {!! Form::close() !!}
                </td>-->
                </tr>
            @endforeach
              
        </tbody>
      
    </table>
    
    
    
@else
    No hay ningún asistente registrado en este Webinar
@endif

@stop
@section('script')
<script>
    function accents_supr(data){
        return ! data ?
        '' :
        typeof data === 'string' ?
        data
            .replace( /\n/g, ' ' )
            .replace( /[áàäâ]/g, 'a' )
            .replace( /[éèëê]/g, 'e' )
            .replace( /[íìïî]/g, 'i' )
            .replace( /[óòöô]/g, 'o' )
            .replace( /[úùüû]/g, 'u' ):
        data;
        jQuery.extend(jQuery.fn.dataTableExt.oSort, {
            "spanish-string-asc"  : function (s1, s2) { return s1.localeCompare(s2); },
            "spanish-string-desc" : function (s1, s2) { return s2.localeCompare(s1); }
        });

        jQuery.fn.DataTable.ext.type.search['spanish-string'] = function ( data ) {
            return accents_supr(data);
        }
    }

    jQuery.fn.DataTable.ext.type.search.string = function ( data ) {
        return ! data ?
        '' :
        typeof data === 'string' ?
        data
            .replace( /έ/g, 'ε' )
            .replace( /[ύϋΰ]/g, 'υ' )
            .replace( /ό/g, 'ο' )
            .replace( /ώ/g, 'ω' )
            .replace( /ά/g, 'α' )
            .replace( /[ίϊΐ]/g, 'ι' )
            .replace( /ή/g, 'η' )
            .replace( /\n/g, ' ' )
            .replace( /á/g, 'a' )
            .replace( /é/g, 'e' )
            .replace( /í/g, 'i' )
            .replace( /ó/g, 'o' )
            .replace( /ú/g, 'u' )
            .replace( /ê/g, 'e' )
            .replace( /î/g, 'i' )
            .replace( /ô/g, 'o' )
            .replace( /è/g, 'e' )
            .replace( /ï/g, 'i' )
            .replace( /ü/g, 'u' )
            .replace( /ã/g, 'a' )
            .replace( /õ/g, 'o' )
            .replace( /ç/g, 'c' )
            .replace( /ì/g, 'i' ) :
        data;
    };

    function exportTableToExcel(tableID, filename = ''){
    var downloadLink;
    var dataType = 'application/vnd.ms-excel';
    var tableSelect = document.getElementById(tableID);
    var tableHTML = tableSelect.outerHTML.replace(/ /g, '%20');
    
    // Specify file name
    filename = filename?filename+'.xls':'excel_data.xls';
    
    // Create download link element
    downloadLink = document.createElement("a");
    
    document.body.appendChild(downloadLink);
    
    if(navigator.msSaveOrOpenBlob){
        var blob = new Blob(['ufeff', tableHTML], {
            type: dataType
        });
        navigator.msSaveOrOpenBlob( blob, filename);
    }else{
        // Create a link to the file
        downloadLink.href = 'data:' + dataType + ', ' + tableHTML;
    
        // Setting the file name
        downloadLink.download = filename;
        
        //triggering the function
        downloadLink.click();
    }
}


</script>
<script>
    

    function exportarexcelFuncion() {
        $(".exportarexcelnuevo").table2excel({
          name: "Worksheet Name",
          filename: "SomeFile.xls"
        });
      }
</script>
<script>
    
    $(document).ready(() => {
        $("#botonExcel").click(function() {
            $("#tablaexportar").table2excel({
                exclude: ".table-striped",
                name: "Worksheet name",
                filename: "Asistentes",
                fileext: ".xls"

            });
        });
    });

</script>
@endsection

local/resources/views/admin/ponentes/crear.blade.php
@extends('layouts.backend')

@section('titulo')
Nuevo Ponente  
@stop


@section('contenido')

@include('alerts.request')

 

 {!! Form::open(['route' => 'ponentes.store', 'method' => 'POST','files'=>true]) !!}
    <div class="form-group">
          {!! Form::label('foto','Foto') !!}
          {!! Form::file('foto')!!}
    </div>  
    <div class="row">
      <div class="col-md-6">  
        <div class="form-group">
                {!! Form::label('apellidos', 'Apellidos:') !!}
                {!! Form::text('apellidos',null,['class'=>'form-control','placeholder'=>'Ingrese Apellidos','required']) !!}
        </div>
      </div>
      <div class="col-md-6">
        <div class="form-group">
                {!! Form::label('nombres', 'Nombres:') !!}
                {!! Form::text('nombres',null,['class'=>'form-control','placeholder'=>'Ingrese Nombres','required']) !!}
        </div>
      </div>
    </div>
    <div class="form-group">
            {!! Form::label('profesion', 'Cargo/Profesión:') !!}
            {!! Form::text('profesion',null,['class'=>'form-control','placeholder'=>'Ingrese la profesion o cargo del ponente','required']) !!}
    </div>
    <div class="row">
      <div class="col-md-6">
        <div class="form-group">
                {!! Form::label('link_fb', 'Link de Facebook:') !!}
                {!! Form::text('link_fb',null,['class'=>'form-control','placeholder'=>'Link de Facebook']) !!}
        </div>
      </div>
      <div class="col-md-6">
        <div class="form-group">
                {!! Form::label('link_tw', 'Link de Twitter:') !!}
                {!! Form::text('link_tw',null,['class'=>'form-control','placeholder'=>'Link de Twitter']) !!}
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-md-6">
        <div class="form-group">
                {!! Form::label('link_inst', 'Link de Instagram:') !!}
                {!! Form::text('link_inst',null,['class'=>'form-control','placeholder'=>'Link de Instagram']) !!}
        </div>
      </div>
      <div class="col-md-6">
        <div class="form-group">
                {!! Form::label('link_linke', 'Link de Linkedin:') !!}
                {!! Form::text('link_linke',null,['class'=>'form-control','placeholder'=>'Link de Linkedin']) !!}
        </div>
      </div>
    </div>
    
    
    {!!Form::submit('Registrar',['class'=>'btn btn-primary'])!!}


            
        
 
{!! Form::close() !!}



@stop

local/resources/views/admin/ponentes/index.blade.php
@extends('layouts.backend')

 

@section('titulo')
Imágenes
@stop

@section('contenido')

@include('alerts.success')

 

<a class="btn btn-primary" href="{{ URL::route('ponentes.create') }}">Nuevo ponente</a>
@if (count($ponentes))
    <table  id="tbbuzon" class="table table-striped table-bordered table-hover display" >
        <thead>
            <tr>
                
                <th>Apellidos</th>
                <th>Nombres</th>
                <th>foto</th>
                <th>profesion</th>
                <th>Facebook</th>
                <th>Twitter</th>
                <th>Instagram</th>
                <th>Linkedin</th>
                <th>ACCIONES</th>
            </tr>
        </thead>

        <tbody>
            @foreach ($ponentes as $ponentes)
                <tr>
                <td>{{ $ponentes->apellidos }}</td>
                <td>{{ $ponentes->nombres }}</td>
                @if(empty($ponentes->foto))
                <td><img src="{{asset('local/public/images')}}/no-imagen.jpg"  style ="width: 100px"></td>
                @else
                <td><img src="{{asset('local/public/images')}}/{{$ponentes->foto}}"  style ="width: 100px"></td>
                @endif
                <td>{{ $ponentes->profesion }}</td>
                <td>{{ $ponentes->link_fb }}</td>
                <td>{{ $ponentes->link_tw}}</td>
                <td>{{ $ponentes->link_inst }}</td>
                <td>{{ $ponentes->link_linke }}</td>
                <td>
                    <a class="btn btn-success" href="{{route('ponentes.edit', $ponentes->id)}}" role="button">
                        <i class="fa fa-pencil-square-o"></i>
                    </a>
                    {!! Form::open(array('method' => 'DELETE', 'route' => array('ponentes.destroy', $ponentes->id))) !!}
                        <button type="submit" onclick="return confirm('Quiere borrar el registro?')" class="btn btn-danger"><span class="fa fa-trash-o"></span></button>
                    {!! Form::close() !!}
                </td>
                </tr>
            @endforeach
              
        </tbody>
      
    </table>
    
    
    
@else
    No hay ningún ponente registrado
@endif

@stop
@section('script')
<script>
    function accents_supr(data){
        return ! data ?
        '' :
        typeof data === 'string' ?
        data
            .replace( /\n/g, ' ' )
            .replace( /[áàäâ]/g, 'a' )
            .replace( /[éèëê]/g, 'e' )
            .replace( /[íìïî]/g, 'i' )
            .replace( /[óòöô]/g, 'o' )
            .replace( /[úùüû]/g, 'u' ):
        data;
        jQuery.extend(jQuery.fn.dataTableExt.oSort, {
            "spanish-string-asc"  : function (s1, s2) { return s1.localeCompare(s2); },
            "spanish-string-desc" : function (s1, s2) { return s2.localeCompare(s1); }
        });

        jQuery.fn.DataTable.ext.type.search['spanish-string'] = function ( data ) {
            return accents_supr(data);
        }
    }

    jQuery.fn.DataTable.ext.type.search.string = function ( data ) {
        return ! data ?
        '' :
        typeof data === 'string' ?
        data
            .replace( /έ/g, 'ε' )
            .replace( /[ύϋΰ]/g, 'υ' )
            .replace( /ό/g, 'ο' )
            .replace( /ώ/g, 'ω' )
            .replace( /ά/g, 'α' )
            .replace( /[ίϊΐ]/g, 'ι' )
            .replace( /ή/g, 'η' )
            .replace( /\n/g, ' ' )
            .replace( /á/g, 'a' )
            .replace( /é/g, 'e' )
            .replace( /í/g, 'i' )
            .replace( /ó/g, 'o' )
            .replace( /ú/g, 'u' )
            .replace( /ê/g, 'e' )
            .replace( /î/g, 'i' )
            .replace( /ô/g, 'o' )
            .replace( /è/g, 'e' )
            .replace( /ï/g, 'i' )
            .replace( /ü/g, 'u' )
            .replace( /ã/g, 'a' )
            .replace( /õ/g, 'o' )
            .replace( /ç/g, 'c' )
            .replace( /ì/g, 'i' ) :
        data;
    };
</script>
@endsection