local/routes/web.php
<?php

Route::get('seleccionarjornada/{id}', 'EventoAsistenciaController@seleccionjornada');
Route::get('asistencia/{id}', 'EventoAsistenciaController@consultaregistro');
Route::get('asistencia/{id}/{usuario}', 'EventoAsistenciaController@registroasistencia');
Route::resource('eventoasistencia', 'EventoAsistenciaController');

Route::get('/', 'PaginasController@index')->name('casa');

Route::post('enviarmensaje',[
	'uses' =>'PaginasController@enviarmensaje',
	'as'   =>'paginas.enviarmensaje'
]);
Route::post('enviarsolicitud',[
	'uses' =>'PaginasController@enviarsolicitud',
	'as'   =>'paginas.enviarsolicitud'
	]);
Route::post('contratarunachay',[
	'uses' =>'PaginasController@contratarunachay',
	'as'   =>'paginas.contratarunachay'
	]);
Route::post('registrarpersona',[
	'uses' =>'RegistroController@guardar',
	'as'   =>'registrarpersona.guardar'
]);
Route::post('registrarfacturacion',[
	'uses' =>'FacturacionController@store',
	'as'   =>'registrarfacturacion.store'
]);
Route::get('administracion', 'BackendController@index');
Route::get('/login', 'HomeController@index');
Auth::routes();
Route::get('/logout', 'Auth\LoginController@logout')->name('logout' );
Route::get('/home', 'HomeController@index')->name('home');
// Route::get('logout', 'LogController@logout');
Route::get('administracion', 'BackendController@index');
Route::resource('categorias','CategoriasController');
Route::get('categorias/{id}/destroy',[
	'uses' =>'CategoriasController@destroy',
	'as'   =>'categorias.destroy'
	]);
Route::resource('articulos', 'ArticulosController');
Route::get('articulos/{id}/destroy',[
			'uses' => 'ArticulosController@destroy',
			'as'   => 'articulos.destroy'
		]);
Route::resource('animacion', 'SliderController');
Route::get('animacion/{id}/destroy',[
			'uses' => 'SliderController@destroy',
			'as'   => 'animacion.destroy'
		]);
Route::resource('informacion', 'InformacionController');
Route::get('informacion/{id}/destroy',[
			'uses' => 'InformacionController@destroy',
			'as'   => 'informacion.destroy'
		]);
Route::get('imagen/{id}/destroy',[
			'uses' => 'ImagenesController@destroy',
			'as'   => 'imagen.destroy'
		]);
Route::resource('video', 'VideoController');
Route::get('video/{id}/destroy',[
			'uses' => 'VideoController@destroy',
			'as'   => 'video.destroy'
		]);
// Route::resource('galeria', 'FotosController');
// Route::get('galeria/{id}/destroy',[
			// 			'uses' => 'FotosController@destroy',
			// 			'as'   => 'galeria.destroy'
		// 		]);
Route::resource('tags', 'TagsController');
Route::get('tags/{id}/destroy',[
			'uses' => 'TagsController@destroy',
			'as'   => 'tags.destroy'
		]);
Route::resource('tipos-usuarios','TiposController');
Route::resource('usuarios','UsuariosController');
Route::resource('camposextrasgrupos','CamposExtrasGruposController');
Route::get('camposextrasgrupos/{id}/destroy',[
			'uses' => 'CamposExtrasGruposController@destroy',
			'as'   => 'camposextrasgrupos.destroy'
		]);
Route::resource('camposextras','CamposExtrasController');
Route::resource('obtener','AjaxController');
Route::get('camposextras/{id}/destroy',[
			'uses' => 'CamposExtrasController@destroy',
			'as'   => 'camposextras.destroy'
		]);
Route::resource('registro','RegistrosController');
Route::get('autorizado','RegistrosController@autorizado');
Route::get('confirmacion/{codigo}', 'RegistrosController@confirmar');
Route::get('contrasena','RegistrosController@contrasena');
Route::post('recuperacion', ['as' => 'GuardarRecuperacion', 'uses' => 'RegistrosController@guardarrecuperacion']);
Route::post('restablecer', ['as' => 'GuardarRestablecer', 'uses' => 'RegistrosController@guardarrestablecer']);
Route::get('env/{id}','RegistrosController@envio');
Route::get('reestablecer/{codigo}','RegistrosController@busqueda');
Route::resource('solicitudes','RegistrosController@solicitudes');
Route::get('habilitarusuario/{id}', ['as' => 'hab_user', 'uses' => 'RegistrosController@habilitar_usuario']);
Route::resource('activaciones','ArticulosController@activaciones');
Route::get('activararticulo/{id}', ['as' => 'hab_articulo', 'uses' => 'RegistrosController@habilitararticulo']);
//Route::post('registro','UsuariosController@registro');
//Route::get('registro', ['as' => 'registro', 'uses' => 'UsuariosController@registro']);
//////////////////
Route::resource('categoriainterna','CategoriaInternaController');
Route::get('categoriainterna/{id}/destroy',[
	'uses' =>'CategoriaInternaController@destroy',
	'as'   =>'categoriainterna.destroy'
	]);
//Route::get('/publica', 'LogController@publicar');
//Route::get('/goo', 'LogController@iniciagoogle');
Route::post('/upload', 'ArticulosController@subirfotogaleria');
Route::post('/uploaddoc', 'ArticulosController@subirdoc');
Route::get('/infoevento', 'PaginasController@infoeventos');
Route::get('/pruebaa', 'ArticulosController@pruebaa');
//Route::get('/contratarunachay', function(){return view('paginas/contratarrunachay'); });
//Route::get('/formulario', function(){return view('paginas/formulario'); });
Route::get('formfacturacion/{id}','FacturacionController@ue');
Route::resource('formregistro','RegistroController');
Route::resource('formfacturacion','FacturacionController');
//Route::get('/formulario-facturacion', function(){return view('paginas/facturacion'); });
// Route::get('/confirmacion', function(){
	// 	return view('paginas/confirmacion');
// });
//Route::get('/formulario-facturacion-mercedarias', function(){return view('paginas/facturacion/mercedarias'); });
// Route::get('/jornada-docentes', function(){
	// 	return view('paginas/conferencia.index');
// });
// Route::get('/confirmaregistro', 'WebinarRegistroController@confirmaregistro');
Route::get('/confirmaregistro/{id}',[
	'uses' => 'WebinarRegistroController@confirmaregistro',
	'as'   => 'webinar.confirmaregistro'
]);
//
Route::resource('WebinarRegistro','WebinarRegistroController');
// Route::get('/confirmacion/', 'WebinarRegistroController@store');
Route::get('lista-asistentes-excel','WebinarController@exportExcel')->name('asistentes.excel');
Route::resource('imagen', 'ImagenesController');
Route::resource('webinar', 'WebinarController');
Route::resource('ponentes', 'PonentesController');
Route::resource('asignarponentes', 'AsignarPonentesController');
Route::resource('asignardias', 'AsignarDiaController');
Route::resource('calificacionponente', 'CalificacionPonenteController');
Route::get('calificaciones-ponente/{id_dia_ponente}/{id_ponente}/',[
			'uses' => 'AsignarPonentesController@mostrar_calificaciones',
			'as'   => 'asignarponentes.mostrar'
		]);
Route::get('ponentes_dia/{id}/',[
			'uses' => 'WebinarController@add',
			'as'   => 'webinar.add'
		]);
Route::get('asistencias/{id}/',[
			'uses' => 'WebinarController@show_asistencia',
			'as'   => 'webinar.asis'
		]);

Route::get('imprimirqr/{id}/',[
			'uses' => 'WebinarRegistroController@descargarqr',
			'as'   => 'WebinarRegistro.qr'
		]);

Route::get('asistentes_cumplidos/{id}/',[
			'uses' => 'WebinarController@show_aprobados',
			'as'   => 'webinar.aprob'
		]);

Route::put('cambiarestado/{id}/',[
			'uses' => 'AsignarDiaController@cambiarestado',
			'as'   => 'asignardias.cambiarestado'
		]);
Route::get('dias_evento/{id}/',[
			'uses' => 'WebinarController@dates',
			'as'   => 'webinar.dates'
		]);
Route::get('asistencia_evento/{id}/',[
			'uses' => 'AsignarDiaController@asis',
			'as'   => 'asignardias.asis'
		]);
Route::get('destroyponente/{id}/',[
			'uses' => 'WebinarController@destroyponente',
			'as'   => 'webinar.destroyponente'
		]);
//Route::get('/transmision', function(){return view("paginas.transmision");});
// Route::get('/enviarasistencia', function(){return view("admin.webinar.enviarasistencia");});
Route::get('enviarasistencia/{id}/{salto}/',[
			'uses' => 'WebinarController@envasistencia',
			'as'   => 'webinar.envasist'
		]);
Route::get('enviarasistenciaunico/{id}/{id_reg}/',[
			'uses' => 'WebinarController@enviarAsistenciaUnico',
			'as'   => 'webinar.envasist1'
		]);

Route::get('enviarcertificado/{id}/{salto}/',[
			'uses' => 'WebinarController@envcertificado',
			'as'   => 'webinar.envcert'
		]);
Route::get('enviarcertificadounico/{id}/{id_reg}/',[
			'uses' => 'WebinarController@envcertificadounico',
			'as'   => 'webinar.envcertunico'
		]);


Route::get('{id}', 'WebinarRegistroController@registrowebinar');

Route::get('reserva/{id}', 'WebinarRegistroController@reserva');

Route::get('{id}/buscar_certificado', 'WebinarRegistroController@generar_certificado');

Route::get('buscarcertificado/{id_evento}/{id_asistente}', 'WebinarRegistroController@pagina_compartir');

Route::post('certificado/',[
			'uses' => 'WebinarRegistroController@certificado',
			'as'   => 'WebinarRegistro.certificado'
		]);

Route::post('descargar/',[
			'uses' => 'WebinarRegistroController@descargar',
			'as'   => 'WebinarRegistro.descargar'
		]);

local/app/Webinar.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Webinar extends Model
{
    //
    protected $table = 'webinar';

    protected $fillable = ['id','slug', 'tema','fecha','hora', 'anuncio', 'estado'];

 	protected $hidden = [];

 	// public function setPathAttribute($path){

  //       if(!empty($path)){
  //         $nombre = $path->getClientOriginalName();
  //         $this->attributes['path'] = $nombre;
  //         \Storage::disk('local')->put($nombre, \File::get($path));
  //       }

  //    }
}

local/app/Http/Controllers/Webinar.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Webinar extends Model
{
    //
    protected $table = 'webinar';

    protected $fillable = ['id','slug', 'tema','fecha','hora', 'hora_fin', 'logo', 'anuncio', 'link', 'estado'];

 	protected $hidden = [];

 	// public function setPathAttribute($path){

  //       if(!empty($path)){
  //         $nombre = $path->getClientOriginalName();
  //         $this->attributes['path'] = $nombre;
  //         \Storage::disk('local')->put($nombre, \File::get($path));
  //       }

  //    }
}

local/resources/views/admin/webinar/asistencia.blade.php
@extends('layouts.backend')

 

@section('titulo')
ASISTENCIA AL DIA DEL EVENTO
@stop

@section('contenido')
<?php
function diaES($fecha){
    $dia = date('l', strtotime($fecha));
    $dias_ES = array("Lunes", "Martes", "Miércoles", "Jueves", "Viernes", "Sábado", "Domingo");
    $dias_EN = array("Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday");
    $nombredia = str_replace($dias_EN, $dias_ES, $dia);
    return $nombredia;
}
function mesES($fecha){
    $mes = date('M', strtotime($fecha));
    $meses_ES = array("Ene", "Feb", "Mar", "Abr", "May", "Jun", "Jul", "Ago", "Sep", "Oct", "Nov", "Dic");
    $meses_EN = array("Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec");
    $nombreMes = str_replace($meses_EN, $meses_ES, $mes);
    return $nombreMes;
}
?>

@include('alerts.success')

 


@if (count($asistencia))

<!--<button id="botonExcel">EXPORTAR</button>-->
<button class="btn btn-primary" id="botonExce" onclick="exportTableToExcel('tablaexportar')">EXPORTAR</button>

<div id="impresionExcelDiv" name="impresionExcelDiv" style="display: none;">
    <table  id="tablaexportar" class="table" >
        <thead>
            <tr>
                
                <th>Cedula</th>
                <th>Comentario</th>
                <th>Registro Asistencia</th>
            </tr>
        </thead>

        <tbody>
            @foreach ($asistenciaex as $asistenciaex)
            <tr>
                <td>{{ $asistenciaex->cedula }}</td>
                <td>{{ $asistenciaex->comentario }}</td>
                <td><?php echo date('d', strtotime($asistenciaex->created_at))." ".mesES($asistenciaex->created_at).", ".date('Y', strtotime($asistenciaex->created_at))." / ".date('G : i', strtotime($asistenciaex->created_at)); ?></td>
            </tr>
            @endforeach
        </tbody>
    </table>
 </div>

    <table  id="tbasis" class="table table-striped table-bordered table-hover display" >
        <thead>
            <tr>
                
                <th>Cedula</th>
                <th>Comentario</th>
                <th>Registro Asistencia</th>
                <!--<th>ACCIONES</th>-->
            </tr>
        </thead>

        <tbody>
            @foreach ($asistencia as $asistencia)
                <tr>
                <td>{{ $asistencia->cedula }}</td>
                <td>{{ $asistencia->comentario }}</td>
                <td><?php echo date('d', strtotime($asistencia->created_at))." ".mesES($asistencia->created_at).", ".date('Y', strtotime($asistencia->created_at))." / ".date('G : i', strtotime($asistencia->created_at)); ?></td>
            
                </tr>
            @endforeach
              
        </tbody>
      
    </table>
    
    
    
@else
    No hay ninguna asistencia registrada en este día
@endif

@stop
@section('script')
<script>
    function accents_supr(data){
        return ! data ?
        '' :
        typeof data === 'string' ?
        data
            .replace( /\n/g, ' ' )
            .replace( /[áàäâ]/g, 'a' )
            .replace( /[éèëê]/g, 'e' )
            .replace( /[íìïî]/g, 'i' )
            .replace( /[óòöô]/g, 'o' )
            .replace( /[úùüû]/g, 'u' ):
        data;
        jQuery.extend(jQuery.fn.dataTableExt.oSort, {
            "spanish-string-asc"  : function (s1, s2) { return s1.localeCompare(s2); },
            "spanish-string-desc" : function (s1, s2) { return s2.localeCompare(s1); }
        });

        jQuery.fn.DataTable.ext.type.search['spanish-string'] = function ( data ) {
            return accents_supr(data);
        }
    }

    jQuery.fn.DataTable.ext.type.search.string = function ( data ) {
        return ! data ?
        '' :
        typeof data === 'string' ?
        data
            .replace( /έ/g, 'ε' )
            .replace( /[ύϋΰ]/g, 'υ' )
            .replace( /ό/g, 'ο' )
            .replace( /ώ/g, 'ω' )
            .replace( /ά/g, 'α' )
            .replace( /[ίϊΐ]/g, 'ι' )
            .replace( /ή/g, 'η' )
            .replace( /\n/g, ' ' )
            .replace( /á/g, 'a' )
            .replace( /é/g, 'e' )
            .replace( /í/g, 'i' )
            .replace( /ó/g, 'o' )
            .replace( /ú/g, 'u' )
            .replace( /ê/g, 'e' )
            .replace( /î/g, 'i' )
            .replace( /ô/g, 'o' )
            .replace( /è/g, 'e' )
            .replace( /ï/g, 'i' )
            .replace( /ü/g, 'u' )
            .replace( /ã/g, 'a' )
            .replace( /õ/g, 'o' )
            .replace( /ç/g, 'c' )
            .replace( /ì/g, 'i' ) :
        data;
    };

    function exportTableToExcel(tableID, filename = ''){
    var downloadLink;
    var dataType = 'application/vnd.ms-excel';
    var tableSelect = document.getElementById(tableID);
    var tableHTML = tableSelect.outerHTML.replace(/ /g, '%20');
    
    // Specify file name
    filename = filename?filename+'.xls':'excel_data.xls';
    
    // Create download link element
    downloadLink = document.createElement("a");
    
    document.body.appendChild(downloadLink);
    
    if(navigator.msSaveOrOpenBlob){
        var blob = new Blob(['ufeff', tableHTML], {
            type: dataType
        });
        navigator.msSaveOrOpenBlob( blob, filename);
    }else{
        // Create a link to the file
        downloadLink.href = 'data:' + dataType + ', ' + tableHTML;
    
        // Setting the file name
        downloadLink.download = filename;
        
        //triggering the function
        downloadLink.click();
    }
}


</script>
<script>
    

    function exportarexcelFuncion() {
        $(".exportarexcelnuevo").table2excel({
          name: "Worksheet Name",
          filename: "SomeFile.xls"
        });
      }
</script>
<script>
    
    $(document).ready(() => {
        $("#botonExcel").click(function() {
            $("#tablaexportar").table2excel({
                exclude: ".table-striped",
                name: "Worksheet name",
                filename: "Asistentes",
                fileext: ".xls"

            });
        });
    });

</script>
@endsection

local/resources/views/admin/webinar/calificaciones.blade.php
@extends('layouts.backend')

 

@section('titulo')
CALIFICACIONES REGISTRADAS PARA ESTE PONENTE
@stop

@section('contenido')
<?php
function diaES($fecha){
    $dia = date('l', strtotime($fecha));
    $dias_ES = array("Lunes", "Martes", "Miércoles", "Jueves", "Viernes", "Sábado", "Domingo");
    $dias_EN = array("Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday");
    $nombredia = str_replace($dias_EN, $dias_ES, $dia);
    return $nombredia;
}
function mesES($fecha){
    $mes = date('M', strtotime($fecha));
    $meses_ES = array("Ene", "Feb", "Mar", "Abr", "May", "Jun", "Jul", "Ago", "Sep", "Oct", "Nov", "Dic");
    $meses_EN = array("Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec");
    $nombreMes = str_replace($meses_EN, $meses_ES, $mes);
    return $nombreMes;
}
?>

@include('alerts.success')

 


@if (count($calificaciones))
@php
$total = count($calificaciones);
@endphp
<br>
<h2>TOTAL CALIFICACIONES <?php echo $total; ?></h2>
<h2>PROMEDIO <?php echo $pro/$total; ?></h2>
<br>
<!--<button id="botonExcel">EXPORTAR</button>-->
<button class="btn btn-primary" id="botonExce" onclick="exportTableToExcel('tablaexportar')">EXPORTAR</button>


<div id="impresionExcelDiv" name="impresionExcelDiv" style="display: none;">
    <table  id="tablaexportar" class="table" >
        <thead>
            <tr>
                
                <th>codigo dia evento</th>
                <th>id ponente</th>
                <th>calificacion</th>
                <th>fecha de calificacion</th>
            </tr>
        </thead>

        <tbody>
            @foreach ($calificacionesex as $exportar)
            <tr>
                <td>{{ $exportar->id_dia_evento }}</td>
                <td>{{ $exportar->id_ponente }}</td>
                <td>{{ $exportar->calificacion }}</td>
                <td><?php echo date('d', strtotime($exportar->created_at))." ".mesES($exportar->created_at).", ".date('Y', strtotime($exportar->created_at))." / ".date('G : i', strtotime($exportar->created_at)); ?></td>
            </tr>
            @endforeach
        </tbody>
    </table>
 </div>

    <table  id="tbcalificaciones" class="table table-striped table-bordered table-hover display" >
        <thead>
            <tr>
                <th>codigo dia evento</th>
                <th>id ponente</th>
                <th>calificacion</th>
                <th>fecha de calificacion</th>
                <!--<th>ACCIONES</th>-->
            </tr>
        </thead>

        <tbody>
        
            @foreach ($calificacionesex as $calif)
            <tr>
                <td>{{ $calif->id_dia_evento }}</td>
                <td>{{ $calif->id_ponente }}</td>
                <td>{{ $calif->calificacion }}</td>
                <td><?php echo date('d', strtotime($calif->created_at))." ".mesES($calif->created_at).", ".date('Y', strtotime($calif->created_at))." / ".date('G : i', strtotime($calif->created_at)); ?></td>
            </tr>
            @endforeach
              
        </tbody>
      
    </table>
    
    
    
@else
    No hay ninguna calificacion para este evento y este ponente
@endif

@stop
@section('script')
<script>
    function accents_supr(data){
        return ! data ?
        '' :
        typeof data === 'string' ?
        data
            .replace( /\n/g, ' ' )
            .replace( /[áàäâ]/g, 'a' )
            .replace( /[éèëê]/g, 'e' )
            .replace( /[íìïî]/g, 'i' )
            .replace( /[óòöô]/g, 'o' )
            .replace( /[úùüû]/g, 'u' ):
        data;
        jQuery.extend(jQuery.fn.dataTableExt.oSort, {
            "spanish-string-asc"  : function (s1, s2) { return s1.localeCompare(s2); },
            "spanish-string-desc" : function (s1, s2) { return s2.localeCompare(s1); }
        });

        jQuery.fn.DataTable.ext.type.search['spanish-string'] = function ( data ) {
            return accents_supr(data);
        }
    }

    jQuery.fn.DataTable.ext.type.search.string = function ( data ) {
        return ! data ?
        '' :
        typeof data === 'string' ?
        data
            .replace( /έ/g, 'ε' )
            .replace( /[ύϋΰ]/g, 'υ' )
            .replace( /ό/g, 'ο' )
            .replace( /ώ/g, 'ω' )
            .replace( /ά/g, 'α' )
            .replace( /[ίϊΐ]/g, 'ι' )
            .replace( /ή/g, 'η' )
            .replace( /\n/g, ' ' )
            .replace( /á/g, 'a' )
            .replace( /é/g, 'e' )
            .replace( /í/g, 'i' )
            .replace( /ó/g, 'o' )
            .replace( /ú/g, 'u' )
            .replace( /ê/g, 'e' )
            .replace( /î/g, 'i' )
            .replace( /ô/g, 'o' )
            .replace( /è/g, 'e' )
            .replace( /ï/g, 'i' )
            .replace( /ü/g, 'u' )
            .replace( /ã/g, 'a' )
            .replace( /õ/g, 'o' )
            .replace( /ç/g, 'c' )
            .replace( /ì/g, 'i' ) :
        data;
    };

    function exportTableToExcel(tableID, filename = ''){
    var downloadLink;
    var dataType = 'application/vnd.ms-excel';
    var tableSelect = document.getElementById(tableID);
    var tableHTML = tableSelect.outerHTML.replace(/ /g, '%20');
    
    // Specify file name
    filename = filename?filename+'.xls':'excel_data.xls';
    
    // Create download link element
    downloadLink = document.createElement("a");
    
    document.body.appendChild(downloadLink);
    
    if(navigator.msSaveOrOpenBlob){
        var blob = new Blob(['ufeff', tableHTML], {
            type: dataType
        });
        navigator.msSaveOrOpenBlob( blob, filename);
    }else{
        // Create a link to the file
        downloadLink.href = 'data:' + dataType + ', ' + tableHTML;
    
        // Setting the file name
        downloadLink.download = filename;
        
        //triggering the function
        downloadLink.click();
    }
}


</script>
<script>
    

    function exportarexcelFuncion() {
        $(".exportarexcelnuevo").table2excel({
          name: "Worksheet Name",
          filename: "SomeFile.xls"
        });
      }
</script>
<script>
    
    $(document).ready(() => {
        $("#botonExcel").click(function() {
            $("#tablaexportar").table2excel({
                exclude: ".table-striped",
                name: "Worksheet name",
                filename: "Asistentes",
                fileext: ".xls"

            });
        });
    });

</script>
@endsection

local/resources/views/admin/webinar/index.blade.php
@extends('layouts.backend')

 

@section('titulo')
Eventos
@stop

@section('contenido')

@include('alerts.success')

 

<a class="btn btn-primary" href="{{ URL::route('webinar.create') }}">Nuevo Evento</a>
@if (count($webi))
    <table  id="tbbuzon" class="table table-striped table-bordered table-hover display" >
        <thead>
            <tr>
                
                <th>Tema</th>
                <th>Fecha</th>
                <th>Hora</th>
                <th>Anuncio</th>
                <th>REGISTRO ACTIVO</th>
                <th>ACCIONES</th>
            </tr>
        </thead>

        <tbody>
            @foreach ($webi as $webi)
                <tr>
                <td>{{ $webi->tema }}</td>
                <td>{{ $webi->fecha }}</td>
                <td>{{ $webi->hora }}</td>
                @if(empty($webi->anuncio))
                <td><img src="{{asset('local/public/images')}}/no-imagen.jpg"  style ="width: 100px"></td>
                @else
                <td><img src="{{asset('local/public/images')}}/{{$webi->anuncio}}"  style ="width: 100px"></td>
                @endif
                <td><?php if ($webi->estado == '1') {
                  echo "SI";
                }else{
                  echo "NO";
                }
                 ?></td>
                <td>
                    <a class="btn btn-success" href="{{route('webinar.edit', $webi->id)}}" role="button">
                        <i class="fa fa-pencil-square-o"></i>
                    </a>
                    {!! Form::open(array('method' => 'DELETE', 'route' => array('webinar.destroy', $webi->id))) !!}
                        <button type="submit" onclick="return confirm('Quiere borrar el registro?')" class="btn btn-danger"><span class="fa fa-trash-o"></span></button>
                    {!! Form::close() !!}
                    <a class="btn btn-success" href="{{route('webinar.show', $webi->id)}}" role="button">
                        REGISTRADOS
                    </a>
                    <!--<a class="btn btn-success" href="{{route('webinar.asis', $webi->id)}}" role="button">
                        ASISTENCIA
                    </a>
                    <a class="btn btn-success" href="{{route('webinar.aprob', $webi->id)}}" role="button">
                        APROBADOS
                    </a>
                    <a class="btn btn-success" href="{{route('webinar.dates', $webi->id)}}" role="button">
                        CONFIGURAR
                    </a>-->
                </td>
                </tr>
            @endforeach
              
        </tbody>
      
    </table>
    
    
    
@else
    No hay ningún Webinar registrado
@endif

@stop
@section('script')
<script>
    function accents_supr(data){
        return ! data ?
        '' :
        typeof data === 'string' ?
        data
            .replace( /\n/g, ' ' )
            .replace( /[áàäâ]/g, 'a' )
            .replace( /[éèëê]/g, 'e' )
            .replace( /[íìïî]/g, 'i' )
            .replace( /[óòöô]/g, 'o' )
            .replace( /[úùüû]/g, 'u' ):
        data;
        jQuery.extend(jQuery.fn.dataTableExt.oSort, {
            "spanish-string-asc"  : function (s1, s2) { return s1.localeCompare(s2); },
            "spanish-string-desc" : function (s1, s2) { return s2.localeCompare(s1); }
        });

        jQuery.fn.DataTable.ext.type.search['spanish-string'] = function ( data ) {
            return accents_supr(data);
        }
    }

    jQuery.fn.DataTable.ext.type.search.string = function ( data ) {
        return ! data ?
        '' :
        typeof data === 'string' ?
        data
            .replace( /έ/g, 'ε' )
            .replace( /[ύϋΰ]/g, 'υ' )
            .replace( /ό/g, 'ο' )
            .replace( /ώ/g, 'ω' )
            .replace( /ά/g, 'α' )
            .replace( /[ίϊΐ]/g, 'ι' )
            .replace( /ή/g, 'η' )
            .replace( /\n/g, ' ' )
            .replace( /á/g, 'a' )
            .replace( /é/g, 'e' )
            .replace( /í/g, 'i' )
            .replace( /ó/g, 'o' )
            .replace( /ú/g, 'u' )
            .replace( /ê/g, 'e' )
            .replace( /î/g, 'i' )
            .replace( /ô/g, 'o' )
            .replace( /è/g, 'e' )
            .replace( /ï/g, 'i' )
            .replace( /ü/g, 'u' )
            .replace( /ã/g, 'a' )
            .replace( /õ/g, 'o' )
            .replace( /ç/g, 'c' )
            .replace( /ì/g, 'i' ) :
        data;
    };
</script>
@endsection